name: 'piper_scheme'
description: 'Piper Ultra Fast And Efficient Text To Speech Library for cross platform any edge device run offline on cpu'
version: '0.0.0'
environment: 
  sdk: '^3.3.0'
dependencies: null
dev_dependencies: 
  lints: '^3.0.0'
  test: '^1.24.0'
repository: 'https://github.com/azkadev/piper'
homepage: 'https://github.com/azkadev/piper'
issue_tracker: 'https://github.com/azkadev/piper/issues'
documentation: 'https://github.com/azkadev/piper/tree/main/docs'
funding: 
  - 'https://github.com/sponsors/azkadev'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
