name: 'piper_flutter'
description: 'Piper Ultra Fast And Efficient Text To Speech Library for cross platform any edge device run offline on cpu'
version: '0.0.0'
homepage: 'https://github.com/azkadev/piper'
repository: 'https://github.com/azkadev/piper'
issue_tracker: 'https://github.com/azkadev/piper/issues'
documentation: 'https://github.com/azkadev/piper/tree/main/docs'
funding: 
  - 'https://github.com/sponsors/azkadev'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment: 
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=1.17.0'
dependencies: 
  flutter: 
    sdk: 'flutter'
dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'
  flutter_lints: '^2.0.0'
flutter: null
